### PR TITLE
Adds new station map Nebulastation

### PR DESCRIPTION
**Pull request by KikoWen0**
## About The Pull Request

Adds a completely brand new multi-z station map "NebulaStation". 
New areas and few exclusive map shuttles (ferry, mining, arrival, evac, cargo)
Few example screenshots
StrongDMM-2024-07-19 20 53 15
StrongDMM-2024-07-19 20 51 41
image
image
image
image
And more...

## Why It's Good For The Game

New maps are always good for the game

## Changelog

:cl: Kiko
add: Nebulastation, new station map
/:cl:

### CODE REVIEW

**Comment by KikoWen0** [comment]
Are we winning chat

**Comment by JupiterJaeden** [comment]
we're so back forkening bros

**Comment by Vect0r2** [comment]
Hello! I would just like to let you know I am looking at this at the moment! We have quite a bit more setup to go though before I will seriously look though this and make sure it's mergable (and hopefully get some better mappers to look over it). But I will let you know when we are ready to start looking though it.

**Comment by MoffNyan** [comment]
YES!!! Really love Nebulastation, so many areas great for gimmicks and generally just having fun with members of the crew

**Comment by grungussuss** [comment]
You need to pull latest master so it updates the checks

**Comment by KikoWen0** [comment]
Github is so nerdy

**Pull request closed without merging**
