### PR TITLE
Buckshot: The Return

### PR DESCRIPTION
**Pull request by GPeckman**
## About The Pull Request

Adds back buckshot and shotgun slugs as crew-available ammunition. They can be printed from security lathes when researched, but the research requires illegal technology. They can also be bought from the black market, although like most things on the market this is subject to random chance.

## Why It's Good For The Game

Security should have some sort of alternative to energy weapons. Also, both Jupiter and Vector expressed interest in re-adding security ballistics on discord:
ballistics_1
ballistics_2

## Changelog

:cl:
add: Buckshot and shotgun slugs can be printed by the crew again. Find it at the security protolathe, but be aware that the research for it requires illegal technology.
add: You can also buy buckshot and slugs from the black market.
/:cl:

### CODE REVIEW

**Comment by uaioy** [comment]
buckshot still suck so, sec can have the ballistics that tickle as a treat i guess

**Comment by ItzRiumz** [comment]
I'm not sure we have the balance necessary for buckshot and slugs yet. They're extremely strong crew ammo and we're going to see antags struggle very heavily against security if we add it back.

**Comment by uaioy** [comment]
> I'm not sure we have the balance necessary for buckshot and slugs yet. They're extremely strong crew ammo and we're going to see antags struggle very heavily against security if we add it back.

buckshots were nerfed into hell pretty sure, it'd be more problematic to give sec regular ballistic guns like pistols

**Comment by ItzRiumz** [comment]
> buckshots were nerfed into hell pretty sure, it'd be more problematic to give sec regular ballistic guns like pistols

The problem is that slugs haven't been nerfed and still deal 60 damage. Plus if it's a close range blast I'm pretty sure it's a short stun which lets you get a follow up to put someone into crit or near crit. Wounds also make buckshot and slugs absolutely horrible since antags don't have easy ways to deal with blood loss unlike the crew.

I love ballistics as much as the next guy but right now our balance still is TG balance currently. Until we add ways for more protection from ballistics or by nerfing them a little I believe we shouldn't be buffing the crew by giving them buckshot and slugs.

**Comment by Blacklist897** [comment]
Dont give them full power buckshot please

**Comment by GPeckman** [comment]
> The problem is that slugs haven't been nerfed and still deal 60 damage

I've nerfed it down to 40 damage.

**Comment by SamsonTheMVP** [comment]
sec guy here, this is a really bad idea, you're giving sec at best an extremely damaging better stun baton and at worst the best ranged crewsided weapon from roundstart (i dont count dragnet here) 
if we're doing this then antagonists should get a massive power increase. like MASSIVE.

**Comment by Formerxboxgamer** [comment]
I’d rather not power creep our way into hell. Let’s not add this

**Comment by Cheshify** [comment]
I think it's too soon to add this

**Comment by GPeckman** [comment]
I wasn't expecting this PR to be so controversial. I've opened a thread for it on discord in the dev-suggestions channel, hopefully we can find a solution there.

**Comment by JupiterJaeden** [comment]
> > The problem is that slugs haven't been nerfed and still deal 60 damage
> 
> I've nerfed it down to 40 damage.

You should add this to the PR body, it's relevant info.

EDIT: and the changelog.

**Comment by Loafin34** [comment]
glycerol here, that was a joke

**Comment by GPeckman** [comment]
> You should add this to the PR body, it's relevant info.
> 
> EDIT: and the changelog.

The damage nerf was made before I locked buckshot behind illegal tech, and has since been removed. 

Although I should clarify that slugs only deal about 50 damage, not 60.

**Comment by breadcrombs** [comment]
add voidshots instead fr fr
https://github.com/tgstation/tgstation/pull/67250

**Comment by Yobrocharlie** [comment]
Slugs are comedically powerful just one or two at PB range can put somebody into hard crit even if they have ballistic armor,
Buckshot is much of the same, if anything I’d be up for the re-addition do autorifles but buckshot and slugs are a fucking S T R E T C H

**Comment by GPeckman** [comment]
I think it's obvious to everyone that this isn't going anywhere

**Comment by grungussuss** [comment]
too bad we couldn't host a codebase vote in time to get this in, sorry!

**Pull request closed without merging**
