### PR TITLE
Adds rabbit infusion to genetics

### PR DESCRIPTION
**Pull request by ValuedEmployee**
## About The Pull Request
A port from Iamgoofball's TG pull request that became stale last year: https://github.com/tgstation/tgstation/pull/79698

BunnySolo
BunnyTrio
BunnyHops
BunnyDescr

Adds a rabbit infusion to Genetics. Infusing rabbits causes you to be able to jump long distances, become a vegetarian, give good hugs, and upset the geneticist.

## Why It's Good For The Game

Expanding the genetics infusion system is good for Genetics gameplay.

## Changelog

:cl: ValuedEmployee, original PR by Iamgoofball, sprites from Honkpocket
add: Adds a rabbit infusion to Genetics. Infusing rabbits causes you to be able to jump long distances, become a vegetarian, give good hugs, and upset the geneticist. Finishing the Rabbit Mutant infusion entry will flag you as a non-human on medical scanners. The jump can have you crash through grills and windows injuring you in the attempt. Infusing rabbits also grants you Transcendent Olfaction.
add: Rabbits now hop around.
/:cl:

### CODE REVIEW

**Comment by ValuedEmployee** [comment]
In advance, work in progress.

**Comment by ValuedEmployee** [comment]
Seems like every failure right now is due to /datum/unit_test/species_change_clothing. Guess there's an issue with keeping your shoes when you transform, but I wonder if that's okay?

**Comment by ValuedEmployee** [comment]
When you get the infusion, only one leg at a time becomes digitigrade. I think that deletes your shoes if you didn't originally have digi legs.

EDIT: You do in fact keep your shoes so I'm confused.

**Comment by ValuedEmployee** [comment]
Wait, am I being gaslit? The shoes are not disappearing.
Screenshot 2024-08-20 at 3 13 15 PM
Screenshot 2024-08-20 at 3 13 32 PM

**Review by grungussuss — CHANGES_REQUESTED** [review]
we're not adding furry races to wallstation 13.
If you still want to advance with this, remove the fur and paws, keep the bunny ears, snout and tail.

**Comment by ValuedEmployee** [comment]
https://discord.com/channels/1271647269845864601/1272756361746186321/1272995879674183722

Jeff was the one who said porting this was a good idea.

**Comment by grungussuss** [comment]
Ok I'll talk to him

**Comment by ValuedEmployee** [comment]
> Wait, am I being gaslit? The shoes are not disappearing. Screenshot 2024-08-20 at 3 13 15 PM Screenshot 2024-08-20 at 3 13 32 PM

I've realized the current issue is that digi legs are not dropping the shoes, and they should.

**Pull request closed without merging**
