### PR TITLE
ADDS BEHEADING

### PR DESCRIPTION
**Pull request by sylvia-from-fulp-station**
## About The Pu
Discord_ZOsxb4pUfL
Discord_elYywwCG40

yeah.......
adds one line to the code for heads allowing them to be dismembered like other limbs.

tested: 
-cranial fissures still exist and happen a few hits before beheading.
-the plasma cutter does not dismember the head at any amount of damage.

## Why It's Good For The Game

it's a scary thing that antagonists or shit sec can do which provides a unique situation for medical to deal with.

a beheading is loud, messy and creates more evidence. cremation / gibbing is still faster rewarding well-planned murder.

there is a cool interaction with lings being able to survive without a head.

## Changelog
:cl:
balance: many melee hits to the head will dismember it.
/:cl:

### CODE REVIEW

**Comment by Metekillot** [comment]
Sounds like a shortcut to easily round remove someone. A lot easier to get rid of a head than a whole body.

**Comment by Loafin34** [comment]
counterpoint: spear with head on it.

**Comment by sylvia-from-fulp-station** [comment]
> Sounds like a shortcut to easily round remove someone. A lot easier to get rid of a head than a whole body.

Well yeah but you can already do this with a bedsheet and a toolbelt, it's just asinine you cant do it with a sharp object

**Review by grungussuss — APPROVED** [review]

**Comment by grungussuss** [comment]
Resolve the .dme conflicts, should be easy to do by pulling upstream and going into the tgstation.dme, then checkmarking your file again

**Comment by alien3301** [comment]
It makes the head splitting pointless since when you get it you're gonna be dead and beheaded completely in 3 seconds. 
And you can already behead someone with a toolbelt or amputation shears but that requires effort unlike beheading someone with just a sharp item.

>a beheading is loud, messy and creates more evidence. cremation / gibbing is still faster rewarding well-planned murder.

It's no more loud than just killing the person. No more messy then just killing them since you used a sharp weapon and left plenty of blood already. And in no way is it slower than using a cremator or gibber

This is like giving changeling absorb but even stronger to everyone on the station.

**Comment by alien3301** [comment]
> provides a unique situation for medical to deal with.

No it doesn't. If they don't have the head there is no situation to deal with at all. It's only interesting if they get a head and no body but that will never actually happen in game

**Comment by grungussuss** [comment]
@sylvia-from-fulp-station please address the feedback once you fix the conflicts

**Comment by breadcrombs** [comment]
> It makes the head splitting pointless since when you get it you're gonna be dead and beheaded completely in 3 seconds. And you can already behead someone with a toolbelt or amputation shears but that requires effort unlike beheading someone with just a sharp item.

I never heard of such things as beheading with a toolbelt but if that is true that defeats the purpose of removing beheading or making it rare if you just get a tool (which also requires no effort), which is already the case for beheading as you have to get a sufficiently sharp weapon.

> This is like giving changeling absorb but even stronger to everyone on the station.

This doesn't give everyone super abilities to instantly rr everybody else, rr via beheading with sharp tools is balanced and deliberate as you have to go through great lengths to sever the head before somehow removing/destroying the brain or hiding a unwieldy head and this is only for a single body. Beheading is the easy part, the actual rr involves hiding or destroying the brain which requires more effort than other ways to keep a player dead for a long time such as gut spilling or husking. You can gutspill multiple bodies with ease during the time to just sever a head before destroying or hiding it. 

another major example used for against beheading is murderboning but if some traitor is running around cutting off everyone's heads but leaving it where their body exactly is(which is like 99% of all murderbones) you only get the burden of having to carry both their head and body which is alot quicker than having to put every organ back into their torso if they get gut spilled

**Comment by Admiral-Gigaton** [comment]
> > It makes the head splitting pointless since when you get it you're gonna be dead and beheaded completely in 3 seconds. And you can already behead someone with a toolbelt or amputation shears but that requires effort unlike beheading someone with just a sharp item.


ghetto surgery, mate

**Comment by Metekillot** [comment]
Rather than exhaust myself by explaining to you why this is a bad idea, I want to withdraw my previous comment.

I think you should merge this. You'll see exactly what I mean.

**Comment by RikuTheKiller** [comment]
> Rather than exhaust myself by explaining to you why this is a bad idea, I want to withdraw my previous comment.
> 
> I think you should merge this. You'll see exactly what I mean.

You do realize beheading was around for years, right? We already know what bringing it back means yet we want it anyway.

**Comment by sylvia-from-fulp-station** [comment]
> It makes the head splitting pointless 

This feature is already pointless, by the time you are head split you are in hard crit and all it does it make your sprite look ugly.

> > a beheading is loud, messy and creates more evidence. cremation / gibbing is still faster rewarding well-planned murder.

> It's no more loud than just killing the person. No more messy then just killing them since you used a sharp weapon and left plenty of blood already. And in no way is it slower than using a cremator or gibber

It takes about twice as many hits to kill as it does to decapitate. The cremator and gibber are near instant. The time spent using those is mostly just getting to either of them.
You leave a decapitated corpse with blood that can be used to pod revive the person.

> This is like giving changeling absorb but even stronger to everyone on the station.

Changeling absorbs permanently removes people from the round. Beheading is not a round removal method unless you use it to destroy a brain, and mind you you can do that with toolbelt in the current version of the game. Beheading with non antag items takes a long time. There is maybe a 10~ second difference between performing the head amputation surgery and just clicking on their head.

> > provides a unique situation for medical to deal with.
> 
> No it doesn't. If they don't have the head there is no situation to deal with at all. It's only interesting if they get a head and no body but that will never actually happen in game

I mean it does regardless of the scenario. getting a decapitated corpse could save someone's life if you use them as an organ donor. getting a body-less head offers the challenge of finding them a body

**Comment by alien3301** [comment]
>I never heard of such things as beheading with a toolbelt but if that is true that defeats the purpose of removing beheading or making it rare if you just get a tool (which also requires no effort), which is already the case for beheading as you have to get a sufficiently sharp weapon.

While you can do all this with a toolbelt it's more balanced with toolbelts. You need to actually have a toolbelt or a box of tools on top of a normal sized bedsheet do it while beheading just needs your weapon which you already have if you killed someone and a small bonesetter to get the brain out and eat it.

> getting a decapitated corpse could save someone's life if you use them as an organ donor.

Medbay can print organs including fleshy ones with some research

> somehow removing/destroying the brain or hiding a unwieldy head and this is only for a single body

Just bonesetter and eat the brain

**Comment by breadcrombs** [comment]
> Just bonesetter and eat the brain

you cant eat the brain unless its deepfried

**Comment by Revel0** [comment]
Decap is good with balance but as it is now it's a little too easy to round remove some poor sot in maint. Decapitation should be around equal with the other methods of round removal sutch as ship gibbing, gibber gibbing, etc. My solution runs more around giving certain weapons that aren't as easy to hide in your back pocket decaping. like chainsaw, claymore and fireaxe. This I think would make decaping as balanced as the other methods of round removal above.

**Pull request closed without merging**
