### PR TITLE
adds rat reagent

### PR DESCRIPTION
**Pull request by tonyhawq**
## About The Pull Request
It adds rats as a reagent like ants.

## Why It's Good For The Game
I think it's a wacky and logical escalation of what we already have in the game while staying balanced by being locked behind later technologies and a huge time sink.

https://github.com/user-attachments/assets/99c50f14-7749-4aca-a6fe-547c7d69d354

Changelog
🆑
add: Added Rats as a new reagent, much like ants but with more lethality, and a much harder recipe.
/🆑

### CODE REVIEW

**Comment by tonyhawq** [comment]
hey mister jeff i think you broke the test suite

**Comment by Vect0r2** [comment]
> hey mister jeff i think you broke the test suite
that uhh is me I broke it- well it was always broken I just haven't fixed it yet

**Comment by Vect0r2** [comment]
> > hey mister jeff i think you broke the test suite

that uhh is me I broke it- well it was always broken I just haven't fixed it yet

**Comment by tonyhawq** [comment]
just push to prod you can trust me on this one

**Comment by Vect0r2** [comment]
I am more than happy to have it TMed while I get everything setup

**Review by grungussuss — CHANGES_REQUESTED** [review]
> I think it's a wacky and logical escalation of what we already have in the game

Wacky, yes.
Logical? No.
It being a reagent means you can foamdupe it, put it into syringes, patches, pills (???). Even if we already have ants, which is also really illogical, at least ants are small enough to make some sense into fitting them in a beaker or syringe. Rats are way too big to do that and it breaks the immersion.
If this was similar to the `life` reagent, it would make more sense in that spilling it would make rats. Or generate rats when ingested, but definitely not outright rats in a beaker.

**Comment by tonyhawq** [comment]
I think increasing the amount of rat juice per real rat mob to 15 could allievate this because really if you think about it you could probably stuff 3 rats in a milk carton (50u) or like 6 or whatever in the Home Depot bucket sized large beaker.

**Comment by grungussuss** [comment]
> I think increasing the amount of rat juice per real rat mob to 15 could allievate this

that means you can stuff a full rat into a syringe and inject it through the nozzle into someone, it also means you can put 3 rats in one pill.

**Comment by tonyhawq** [comment]
In any case, I don’t think there is anything suggesting that it is literally rats in a beaker besides the flavor text of it having a fuzzy flavor, it could easily be rat serum that activates when spilled or ingested. The 15u change would actually lean towards it being rat juice as you can’t split a rat in half by pouring half of it in another beaker.

**Comment by tonyhawq** [comment]
I mean in real life. Before, you could split a rat into whatever the precision byond allows

**Comment by grungussuss** [comment]
> In any case, I don’t think there is anything suggesting that it is literally rats in a beaker besides the flavor text of it having a fuzzy flavor.

image
your code suggests it's literally live rats inside your stomach on ingestion.
in the case of ants there is so many of them that splitting it into 1 unit still makes sense that there is a lot of them in one unit, given that it needs to be at least 15 units of "rat juice" it wouldn't make sense to be live rats. That's why I'm suggesting you make it similar to the `life` reagent.

**Comment by tonyhawq** [comment]
The flavor text can be changed to make it seem more like rats are being generated inside of you.

**Comment by grungussuss** [comment]
conflict

**Comment by grungussuss** [comment]
also pull latest master so the screenshot tests don't fail

**Comment by tonyhawq** [comment]
In the name of the lord, Jesus Christ, I will fix this merge conflict🙏

**Comment by tonyhawq** [comment]
Now that I’ve accepted it being rat juice I’m also going to lower it from 15u to 8u per rat, so it’s still only 1 rat per syringe but more should spawn from splashes and the like.

**Comment by tonyhawq** [comment]
The CI Suite / Integration Tests (multiz_debug) / run_integration_tests (pull_request) test seems to be flaky, after adding autodoc comments it seems to pass after failing before.

**Comment by grungussuss** [comment]
badass

**Pull request merged**
