### PR TITLE
[SEMI-MODULAR] Ports Flavor Text from Nova sector, with my adapations from TaleStation

### PR DESCRIPTION
**Pull request by Jolly-66**
## About The Pull Request
Title.

## Why It's Good For The Game

https://discord.com/channels/1271647269845864601/1273632796992213053/1273632800599310357

Flavor text is a cool roleplay thing to have/use. This is a port of Nova sectors implementation of it, but with the scrubbing of the ERP stuff I did on TaleStation.

This includes the panel, prefs inputs, etc. If its wanted, I can also port https://github.com/TaleStation/TaleStation/pull/5665 which makes flavor text not get obscured for miniscle things on your face (like gum, flowers, ect). Its annoying, honestly, but still a good feature nonetheless.

image

## Changelog

:cl: Jolly
add: Ported flavor text from Nova Sector, implementation taken from TaleStation (no gross weird stuff).
/:cl:

### CODE REVIEW

**Comment by tontyGH** [comment]
This is how Wallstation turns into ERPStation... it's over...

**Comment by Cheshify** [comment]
Roleplay content for people who want it, and a honeypot for shitters, why not?

**Comment by grungussuss** [comment]
TGUI check failing

**Comment by grungussuss** [comment]
probably fine

**Pull request merged**
