### PR TITLE
Adds blahaj to the loadout

### PR DESCRIPTION
**Pull request by JackEnoff**
## About The Pull Request

Revival of https://github.com/wallstation13/wallstation13/pull/36 , now modularized

## Why It's Good For The Game

Funny and cute shark

## Changelog

:cl:
add: Added Blahaj to the loadout menu. Rejoice!
/:cl:

### CODE REVIEW

**Comment by Artemchik542** [comment]
I think it would be better to give your module a more appropriate name. So that someone in the future can add more plushes, hats and other cool things to it. For example: `extra_loadout/` `wall_loadout/` and etc.

**Review by grungussuss — APPROVED** [review]

**Comment by grungussuss** [comment]
merge conflict

**Comment by JackEnoff** [comment]
pressed wrong button because I was working on other shit at the moment my bad 😐

**Comment by grungussuss** [comment]
failed check: untick `rat_reagent.dm` and your modular file, then retick both again and push

**Pull request merged**
