### PR TITLE
Adds Blahaj to the loadout menu.

### PR DESCRIPTION
**Pull request by Astrogem2**
## About The Pull Request
Adds the shark plush to the loadout menu (Blahaj our beloved).

## Why It's Good For The Game
It's one of the most iconic plushies out there, both in game and out, and it doesn't make sense why its left out of the loadout menu when most of the others that aren't made with special interactions are in.

## Changelog

:cl:
add: Added Blahaj to the loadout menu. Rejoice!
/:cl:

### CODE REVIEW

**Review by grungussuss — APPROVED** [review]

**Review by grungussuss — CHANGES_REQUESTED** [review]
wait no, you gotta make this modular. put the same batch of code in a new .dm file in the wallstation modules file

**Comment by Cheshify** [comment]
This could probably be upstream

**Comment by Astrogem2** [comment]
> wait no, you gotta make this modular. put the same batch of code in a new .dm file in the wallstation modules file

Do I copy that code into a new file, or do I cut it out and put it into that new file?

**Comment by JackEnoff** [comment]
> This could probably be upstream

It was already tried... 
https://github.com/tgstation/tgstation/pull/84717

**Comment by Astrogem2** [comment]
im broke!

**Comment by Astrogem2** [comment]
I'm worried about the authenticity of the code I'm writing since the fork I've downloaded doesn't feel right for testing so I'll wait till tomorrow to push my code again.

**Comment by Loafin34** [comment]
feature creep

**Comment by Astrogem2** [comment]
I don't really get code I guess, was fun while I tried :P

**Pull request closed without merging**
